name: Code Quality Check

on:
  push:
    branches:
      - main
      - 'claude/**'
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20'

jobs:
  check:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome checks (lint + format)
        run: npx biome ci

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
